# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 372d2c9e914dc50c804a0820967fecf7d2308f3285afda0a79a31748e8a679dc1537680906bbf74c740dc6eb7673854c0468fe51a9c6734d1099f62bd0f473a3

test:
  secret_key_base: 55edfc6481362460a9f6d408150f34a18dafbf15a639b4a31a26e517804223127d3d6fb6638a7a41fa8c4132e2c443cabcfd9e38e69899325b3dde1f029a7e16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
